semantic_segmentation_node:
  ros__parameters:
    config_file: ~/aart25_mercator_ws/src/navigation/perception/segmentation/semantic_segmentation/model_config/mask2former/mask2former_swin-l-in22k-384x384-pre_2xb20-80k_wildscenes_standard-512x512.py
    checkpoint_file: ~/aart25_mercator_ws/src/navigation/perception/segmentation/semantic_segmentation/pretrained_models/mask2former_swin_wildscenes.pth
    input_topic: /front_zed/zed_node/rgb/image_rect_color
    output_topic: /segmentation/image
    confidence_topic: /segmentation/confidence
    image_width: 640
    image_height: 360
